version: "3.8"
services:
  zookeeper-1:
    container_name: zookeeper-1
    image: gmanish/zookeeper:2.7.0
    build:
      context: ./zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    volumes:
      - ./config/zookeeper-1/zookeeper.properties:/kafka/config/zookeeper.properties
      - ./data/zookeeper-1/:/tmp/zookeeper/
    networks:
      - kafka

  kafka-1:
    container_name: kafka-1
    image: gmanish/kafka:2.7.0
    build:
      context: .
    depends_on:
      - zookeeper-1
    ports:
      - 29092:29092
      - 29093:29093
    volumes:
      - ./config/kafka-1/server.properties:/kafka/config/server.properties
      - ./data/kafka-1/:/tmp/kafka-logs/
    networks:
      - kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,EXTERNAL_DIFFERENT_HOST://:29093,INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092,EXTERNAL_DIFFERENT_HOST://ec2-44-196-98-202.compute-1.amazonaws.com:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT,EXTERNAL_DIFFERENT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

  kafka-2:
    container_name: kafka-2
    image: gmanish/kafka:2.7.0
    build:
      context: .
    depends_on:
      - zookeeper-1
    ports:
      - 29094:29094
    volumes:
      - ./config/kafka-2/server.properties:/kafka/config/server.properties
      - ./data/kafka-2/:/tmp/kafka-logs/
    networks:
      - kafka
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29094,EXTERNAL_DIFFERENT_HOST://:29094,INTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9094,EXTERNAL_SAME_HOST://localhost:29094,EXTERNAL_DIFFERENT_HOST://ec2-44-196-98-202.compute-1.amazonaws.com:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT,EXTERNAL_DIFFERENT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

  kafka-3:
    container_name: kafka-3
    image: gmanish/kafka:2.7.0
    build:
      context: .
    depends_on:
      - zookeeper-1
    ports:
      - 29095:29095
    volumes:
      - ./config/kafka-3/server.properties:/kafka/config/server.properties
      - ./data/kafka-3/:/tmp/kafka-logs/
    networks:
      - kafka
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29095,INTERNAL://:9095
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9095,EXTERNAL_SAME_HOST://localhost:29095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

networks:
  kafka:
    name: kafka